export default {
  appName: "Spiritual.bot",
  description: "Learn the art of Tarot with AI.",
  theme: {
    modes: {
      light: {
        background: "#ffffff",
        foreground: "#333333",
        card: "#f9fafb",
        cardForeground: "#333333",
        popover: "#f9fafb",
        popoverForeground: "#333333",
        primary: "#ce5905",
        primaryForeground: "#ffffff",
        secondary: "#1d1d1d",
        secondaryForeground: "#ffffff",
        muted: "#f1f5f9",
        mutedForeground: "#7b7b7b",
        accent: "#edfafe",
        accentForeground: "#333333",
        destructive: "#e63946",
        destructiveForeground: "#ffffff",
        border: "#1d1d1d",
        input: "#1d1d1d",
        ring: "#1d1d1d",
        radius: "0.5rem",
      },
      dark: {
        background: "#000000",
        foreground: "#eeeeee",
        card: "#1f2937",
        cardForeground: "#f7f9fb",
        popover: "#1f2937",
        popoverForeground: "#f7f9fb",
        primary: "#30D5C8",
        primaryForeground: "#eeeeee",
        secondary: "#fff",
        secondaryForeground: "#333333",
        muted: "#788597",
        mutedForeground: "#a9b0ba",
        accent: "#111827",
        accentForeground: "#e26912",
        destructive: "#e63946",
        destructiveForeground: "#f7f9fb",
        border: "#ffffff",
        input: "#ffffff",
        ring: "#ffffff",
        radius: "0.5rem",
      },
    },
    // default mode
    defaultMode: "light",
  },
};
