// Thoth Deck
export const tarotDeck = [
  // Major Arcana
  "The Fool",
  "The Magus",
  "The Priestess",
  "The Empress",
  "The Emperor",
  "The Hierophant",
  "The Lovers",
  "The Chariot",
  "Adjustment",
  "The Hermit",
  "Fortune",
  "Lust",
  "The Hanged Man",
  "Death",
  "Art",
  "The Devil",
  "The Tower",
  "The Star",
  "The Moon",
  "The Sun",
  "The Aeon",
  "The Universe",

  // Minor Arcana - Wands
  "Ace of Wands",
  "Two of Wands",
  "Three of Wands",
  "Four of Wands",
  "Five of Wands",
  "Six of Wands",
  "Seven of Wands",
  "Eight of Wands",
  "Nine of Wands",
  "Ten of Wands",
  "Princess of Wands",
  "Prince of Wands",
  "Queen of Wands",
  "Knight of Wands",

  // Minor Arcana - Cups
  "Ace of Cups",
  "Two of Cups",
  "Three of Cups",
  "Four of Cups",
  "Five of Cups",
  "Six of Cups",
  "Seven of Cups",
  "Eight of Cups",
  "Nine of Cups",
  "Ten of Cups",
  "Princess of Cups",
  "Prince of Cups",
  "Queen of Cups",
  "Knight of Cups",

  // Minor Arcana - Swords
  "Ace of Swords",
  "Two of Swords",
  "Three of Swords",
  "Four of Swords",
  "Five of Swords",
  "Six of Swords",
  "Seven of Swords",
  "Eight of Swords",
  "Nine of Swords",
  "Ten of Swords",
  "Princess of Swords",
  "Prince of Swords",
  "Queen of Swords",
  "Knight of Swords",

  // Minor Arcana - Disks (Pentacles in traditional decks)
  "Ace of Disks",
  "Two of Disks",
  "Three of Disks",
  "Four of Disks",
  "Five of Disks",
  "Six of Disks",
  "Seven of Disks",
  "Eight of Disks",
  "Nine of Disks",
  "Ten of Disks",
  "Princess of Disks",
  "Prince of Disks",
  "Queen of Disks",
  "Knight of Disks",
];

const thothCards = [
  "The Fool",
  "The Magus",
  "The High Priestess",
  "The Empress",
  "The Emperor",
  "The Hierophant",
  "The Lovers",
  "The Chariot",
  "Adjustment",
  "The Hermit",
  "Fortune",
  "Lust",
  "The Hanged Man",
  "Death",
  "Art",
  "The Devil",
  "The Tower",
  "The Star",
  "The Moon",
  "The Sun",
  "The Aeon",
  "The Universe",
  "Ace of Wands",
  "Two of Wands",
  "Three of Wands",
  "Four of Wands",
  "Five of Wands",
  "Six of Wands",
  "Seven of Wands",
  "Eight of Wands",
  "Nine of Wands",
  "Ten of Wands",
  "Princess of Wands",
  "Prince of Wands",
  "Queen of Wands",
  "Knight of Wands",
  "Ace of Cups",
  "Two of Cups",
  "Three of Cups",
  "Four of Cups",
  "Five of Cups",
  "Six of Cups",
  "Seven of Cups",
  "Eight of Cups",
  "Nine of Cups",
  "Ten of Cups",
  "Princess of Cups",
  "Prince of Cups",
  "Queen of Cups",
  "Knight of Cups",
  "Ace of Swords",
  "Two of Swords",
  "Three of Swords",
  "Four of Swords",
  "Five of Swords",
  "Six of Swords",
  "Seven of Swords",
  "Eight of Swords",
  "Nine of Swords",
  "Ten of Swords",
  "Princess of Swords",
  "Prince of Swords",
  "Queen of Swords",
  "Knight of Swords",
  "Ace of Disks",
  "Two of Disks",
  "Three of Disks",
  "Four of Disks",
  "Five of Disks",
  "Six of Disks",
  "Seven of Disks",
  "Eight of Disks",
  "Nine of Disks",
  "Ten of Disks",
  "Princess of Disks",
  "Prince of Disks",
  "Queen of Disks",
  "Knight of Disks",
];

const riderWaiteCards = [
  "The Fool",
  "The Magician",
  "The High Priestess",
  "The Empress",
  "The Emperor",
  "The Hierophant",
  "The Lovers",
  "The Chariot",
  "Strength",
  "The Hermit",
  "Wheel of Fortune",
  "Justice",
  "The Hanged Man",
  "Death",
  "Temperance",
  "The Devil",
  "The Tower",
  "The Star",
  "The Moon",
  "The Sun",
  "Judgement",
  "The World",
  "Ace of Wands",
  "Two of Wands",
  "Three of Wands",
  "Four of Wands",
  "Five of Wands",
  "Six of Wands",
  "Seven of Wands",
  "Eight of Wands",
  "Nine of Wands",
  "Ten of Wands",
  "Page of Wands",
  "Knight of Wands",
  "Queen of Wands",
  "King of Wands",
  "Ace of Cups",
  "Two of Cups",
  "Three of Cups",
  "Four of Cups",
  "Five of Cups",
  "Six of Cups",
  "Seven of Cups",
  "Eight of Cups",
  "Nine of Cups",
  "Ten of Cups",
  "Page of Cups",
  "Knight of Cups",
  "Queen of Cups",
  "King of Cups",
  "Ace of Swords",
  "Two of Swords",
  "Three of Swords",
  "Four of Swords",
  "Five of Swords",
  "Six of Swords",
  "Seven of Swords",
  "Eight of Swords",
  "Nine of Swords",
  "Ten of Swords",
  "Page of Swords",
  "Knight of Swords",
  "Queen of Swords",
  "King of Swords",
  "Ace of Pentacles",
  "Two of Pentacles",
  "Three of Pentacles",
  "Four of Pentacles",
  "Five of Pentacles",
  "Six of Pentacles",
  "Seven of Pentacles",
  "Eight of Pentacles",
  "Nine of Pentacles",
  "Ten of Pentacles",
  "Page of Pentacles",
  "Knight of Pentacles",
  "Queen of Pentacles",
  "King of Pentacles",
];

export const deckCardsMapping = {
  thoth: thothCards,
  ryder_waite: riderWaiteCards,
};
