const tarotSpreads = [
  {
    name: "Single Card Spread",
    description: "Draw a single card to gain insight into a specific situation or question.",
    value: "single_card",
    numberOfCards: 1,
    cardMeanings: ["This card represents the current energy or answer to the question at hand."],
  },
  {
    name: "Three Card Spread",
    description: "This spread is used to explore past, present, and future influences surrounding a situation.",
    value: "three_card",
    numberOfCards: 3,
    cardMeanings: [
      "Past: The events or conditions that have led to the current situation.",
      "Present: The current situation or the querent's mindset.",
      "Future: The potential outcome or direction of the situation.",
    ],
  },
  // {
  //   name: "Celtic Cross Spread",
  //   description:
  //     "One of the most detailed and complex spreads, used for a variety of questions, showing many aspects of a situation.",
  //   value: "celtic_cross",
  //   numberOfCards: 10,
  //   cardMeanings: [
  //     "The present situation.",
  //     "Immediate challenge or obstacle.",
  //     "Past influences that are part of the cause.",
  //     "Recent past that formed the foundation.",
  //     "Goals or destiny; what can be achieved under ideal circumstances.",
  //     "Future influences or near future events.",
  //     "The querent's approach or how they are dealing with the situation.",
  //     "External influences; the attitudes and thoughts of others towards the situation.",
  //     "Hopes or fears around the situation.",
  //     "Final outcome, summarizing the other cards.",
  //   ],
  // },
  // {
  //   name: "Horseshoe Spread",
  //   description:
  //     "This spread provides a more detailed overview of a situation, covering past, present, challenges, future, and potential outcomes.",
  //   value: "horseshoe",
  //   numberOfCards: 7,
  //   cardMeanings: [
  //     "Past situation affecting the issue.",
  //     "Present situation or challenge.",
  //     "Hidden influences, things you may not be aware of.",
  //     "Recent past events.",
  //     "Suggested approach or attitude.",
  //     "What is working against you.",
  //     "The likely outcome based on current strategies.",
  //   ],
  // },
  // {
  //   name: "Relationship Spread",
  //   description: "This spread is designed to explore the dynamics and future of a relationship.",
  //   value: "relationship",
  //   numberOfCards: 6,
  //   cardMeanings: [
  //     "How you see yourself in the relationship.",
  //     "How you see your partner.",
  //     "How your partner sees themselves.",
  //     "How your partner sees you.",
  //     "Current status or challenge of the relationship.",
  //     "Future direction of the relationship.",
  //   ],
  // },
  // {
  //   name: "Birthday Spread",
  //   description: "Used to forecast and provide insights into the coming year on someone's birthday.",
  //   value: "birthday",
  //   numberOfCards: 12,
  //   cardMeanings: [
  //     "January: Theme of the month.",
  //     "February: Theme of the month.",
  //     "March: Theme of the month.",
  //     "April: Theme of the month.",
  //     "May: Theme of the month.",
  //     "June: Theme of the month.",
  //     "July: Theme of the month.",
  //     "August: Theme of the month.",
  //     "September: Theme of the month.",
  //     "October: Theme of the month.",
  //     "November: Theme of the month.",
  //     "December: Theme of the month.",
  //   ],
  // },
  // {
  //   name: "Star Spread",
  //   description:
  //     "Used for spiritual self-discovery and personal growth, exploring various aspects of personal spirituality.",
  //   value: "star",
  //   numberOfCards: 7,
  //   cardMeanings: [
  //     "Your self image.",
  //     "Your aspirations.",
  //     "Your ideals and dreams.",
  //     "What grounds you.",
  //     "Your strengths and assets.",
  //     "What you should embrace.",
  //     "What you need to avoid.",
  //   ],
  // },
  // {
  //   name: "Mandala Spread",
  //   description: "Used for deep spiritual exploration and answering questions about the self and the universe.",
  //   value: "mandala",
  //   numberOfCards: 9,
  //   cardMeanings: [
  //     "Self: Represents your inner self.",
  //     "Ambitions: What you desire or strive for.",
  //     "Ideals and Goals: Your spiritual or career goals.",
  //     "Real Achievements: What you have achieved to date.",
  //     "Dependencies: What you rely on.",
  //     "Strengths: Your inner strengths.",
  //     "Weaknesses: Personal weaknesses.",
  //     "Self-Perception: How you perceive yourself.",
  //     "Outcome: What you are working towards.",
  //   ],
  // },
  // {
  //   name: "Tree of Life Spread",
  //   description: "This spread is based on the Kabbalistic Tree of Life structure and is used for spiritual insight.",
  //   value: "tree_of_life",
  //   numberOfCards: 10,
  //   cardMeanings: [
  //     "Kether: Your highest self.",
  //     "Chokmah: Wisdom and inspiration.",
  //     "Binah: Understanding, insight.",
  //     "Chesed: Mercy.",
  //     "Gevurah: Strength, courage.",
  //     "Tiphereth: Beauty, balance.",
  //     "Netzach: Persistence.",
  //     "Hod: Splendor.",
  //     "Yesod: Foundation.",
  //     "Malkuth: Kingdom, material world.",
  //   ],
  // },
  // {
  //   name: "Cross and Triangle Spread",
  //   description: "This spread is used to examine a specific question or situation from several angles.",
  //   value: "cross_and_triangle",
  //   numberOfCards: 9,
  //   cardMeanings: [
  //     "Your current position.",
  //     "Your aspirations.",
  //     "What is evolving.",
  //     "What needs attention.",
  //     "Your base or foundation.",
  //     "What is passing.",
  //     "Your future possibilities.",
  //     "What you should know.",
  //     "The final outcome.",
  //   ],
  // },
];

export default tarotSpreads;
